name: Versatile Pyinstaller Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.9'
        spec: 'pyinstaller/windows10/windows.spec'
        requirements: 'pyinstaller/windows10/requirements.txt'
        upload_exe_with_name: 'sanpy-windows'
