name: Windows Pyinstaller Exe Build

on: 
  # workflow_run:
  #   workflows: ["Test with flake8 and pytest (cudmore)"]
  #   types: [completed]
  #   branches: [main]
  push:
   branches: [master]
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:

    - name: Create Executable
      uses: jtle00/pyinstaller@v1
      with:
        python_ver: '3.9'
        spec: 'pyinstaller/windows10/windows.spec'
        requirements: 'pyinstaller/windows10/requirements.txt'
        upload_exe_with_name: 'sanpy-windows'

