# create a release when we get a push with a v* tag
# see tutorial: https://github.com/marketplace/actions/create-release

name: Full Pyinstaller Release Action

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  # push:
      tags:
        - 'v*'
  workflow_run:
    workflows: ["Test"]
    types: [completed]
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Create Executable
      uses: jtle00/pyinstaller@v1
      with:
         python_ver: '3.9'
         spec: 'pyinstaller/windows10/windows.spec'
         requirements: 'pyinstaller/windows10/requirements.txt'
         upload_exe_with_name: 'sanpy-windows'
            
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "sanpy-windows"
        bodyFile: "CHANGELOG.md"
