name: Windows Pyinstaller Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    # - uses: actions/checkout@v3
    # - uses: actions/setup-python@v4 
    #   with:
    #     python-version: '3.9' 
    # - name: Install dependencies
    #   run: |
    #     pip install -e '.[gui]'

    - name: Create Executable
      uses: jtle00/pyinstaller@v1.0.0
      with:
        python_ver: '3.9'
        spec: 'pyinstaller/windows10/windows.spec'
        requirements: 'pyinstaller/windows10/requirements.txt'
        upload_exe_with_name: 'sanpy-windows'
